image:
  registry: cr.weaviate.io
  tag: 1.26.1
  repo: semitechnologies/weaviate
  pullPolicy: IfNotPresent
  pullSecrets: []

replicas: 1
updateStrategy:
  type: RollingUpdate
resources:
  requests:
    cpu: '500m'
    memory: '200Mi'
  limits:
    cpu: '1000m'
    memory: '200Mi'

service:
  name: weaviate
  ports:
    - name: http
      protocol: TCP
      port: 80
  type: LoadBalancer
  loadBalancerSourceRanges: []
  annotations: {}

grpcService:
  enabled: true
  name: weaviate-grpc
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
  type: LoadBalancer
  loadBalancerSourceRanges: []
  annotations: {}

env:
  ENABLE_API_BASED_MODULES: true
  ASYNC_INDEXING: true

modules:
  text2vec-ollama:
    enabled: true

  generative-ollama:
    enabled: true
